FROM golang:1.13 AS builder

ENV GOPATH=
ENV GOROOT=

COPY . ./

# build and ensure binary is fully linked
RUN CGO_ENABLED=0 go build -v -o /go/bin ./...

FROM alpine

COPY --from=builder /go/bin/event-receiver /go/bin/event-receiver

WORKDIR /go/bin

USER 1000

EXPOSE 8090

CMD ["./event-receiver"]
