---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    downscaler/uptime: Mon-Fri 08:00-18:00 Europe/London
  name: event-multicast
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: event-multicast
    spec:
      volumes:
        - name: event-configmap-volume
          configMap:
            name: event-configmap
      containers:
        - name: event-receiver
          image: event-receiver:latest
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 60
          imagePullPolicy: Never
          securityContext:
            runAsNonRoot: true
          ports:
            - containerPort: 8080
          env:
            - name: EVENT_AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: ecs-secret
                  key: aws_key
            - name: EVENT_AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: ecs-secret
                  key: aws_secret
            - name: EVENT_DIR
              value: /etc/events
          volumeMounts:
            - name: event-configmap-volume
              mountPath: /etc/events
        - name: event-multicast
          image: event-multicast:latest
          imagePullPolicy: Never
          securityContext:
            runAsNonRoot: true
          env:
            - name: EVENT_AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: ecs-secret
                  key: aws_key
            - name: EVENT_AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: ecs-secret
                  key: aws_secret
            - name: CALLBACK_AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: ecs-secret
                  key: aws_key
            - name: CALLBACK_AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: ecs-secret
                  key: aws_secret
            - name: EVENT_DIR
              value: /etc/events
          volumeMounts:
            - name: event-configmap-volume
              mountPath: /etc/events
        - name: callback-sender
          image: callback-sender:latest
          imagePullPolicy: Never
          securityContext:
            runAsNonRoot: true
          env:
            - name: CALLBACK_AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: ecs-secret
                  key: aws_key
            - name: CALLBACK_AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: ecs-secret
                  key: aws_secret
